### ISSUE TITLE
ValueError: Data must be aligned to block boundary in ECB mode

### ISSUE THREAD

**Issue by shangui999** [tagphi/czdb_searcher_python#1]
```python
import sys
from czdb.db_searcher import DbSearcher

database_path = "./communityIpDbFile"  # DBversion = v2024106
query_type = "MEMORY"
key = "xxxxxxxxxxxxxxx=="
ip = ("114.114.114.114")

db_searcher = DbSearcher(database_path, query_type, key)

try:
    region = db_searcher.search(ip)
    print("搜索结果：")
    print(region)
except Exception as e:
    print(f"An error occurred during the search: {e}")

db_searcher.close()
``` 

Traceback (most recent call last):
  File "/Users/xxx/codes/python/chromego_merge/t1.py", line 9, in <module>
    db_searcher = DbSearcher(database_path, query_type, key)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/codes/python/chromego_merge/czdb/db_searcher.py", line 23, in __init__
    header_block = HyperHeaderDecoder.decrypt(self.raf, key)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/codes/python/chromego_merge/czdb/utils/hyper_header_decoder.py", line 22, in decrypt
    decrypted_block = DecryptedBlock.decrypt(key, encrypted_bytes)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/codes/python/chromego_merge/czdb/entity/decrypted_block.py", line 33, in decrypt
    decrypted_bytes = cipher.decrypt(encrypted_bytes)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/chromego_merge_v2/lib/python3.11/site-packages/Crypto/Cipher/_mode_ecb.py", line 197, in decrypt
    raise ValueError("Data must be aligned to block boundary in ECB mode")
ValueError: Data must be aligned to block boundary in ECB mode

**Comment by gaogaoyt** [comment]
看下库和密钥是否为同一版本
